name = "lidire-app"
main = "index.js"
compatibility_date = "2026-09-18"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "lidire-app"
database_id = "1a095fd7-b0a0-4b83-b610-1b3a43fbb716"
